# Generated by Django 5.1.1 on 2024-09-28 08:42

import wagtail.fields
from django.db import migrations


class Migration(migrations.Migration):

    dependencies = [
        ('home', '0003_homepage_hero_title_homepage_sub_title'),
    ]

    operations = [
        migrations.AddField(
            model_name='homepage',
            name='hhw_paragraaf',
            field=wagtail.fields.RichTextField(blank=True, verbose_name='Hoe het werkt'),
        ),
        migrations.AlterField(
            model_name='homepage',
            name='hero_title',
            field=wagtail.fields.RichTextField(blank=True, verbose_name='Hero sectie titel'),
        ),
        migrations.AlterField(
            model_name='homepage',
            name='sub_title',
            field=wagtail.fields.RichTextField(blank=True, verbose_name='Sub titel'),
        ),
    ]
