# Generated by Django 5.1.1 on 2024-09-28 08:57

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('home', '0004_homepage_hhw_paragraaf_alter_homepage_hero_title_and_more'),
    ]

    operations = [
        migrations.AddField(
            model_name='homepage',
            name='hhw_titel',
            field=models.CharField(blank=True, max_length=255, verbose_name='HHW Paragraaf titel'),
        ),
    ]
