# Generated by Django 5.1.1 on 2024-10-02 08:01

import django.db.models.deletion
import wagtail.fields
from django.db import migrations, models


class Migration(migrations.Migration):

    initial = True

    dependencies = [
        ('wagtailcore', '0094_alter_page_locale'),
    ]

    operations = [
        migrations.CreateModel(
            name='HowTo',
            fields=[
                ('page_ptr', models.OneToOneField(auto_created=True, on_delete=django.db.models.deletion.CASCADE, parent_link=True, primary_key=True, serialize=False, to='wagtailcore.page')),
                ('hero_title', wagtail.fields.RichTextField(blank=True, verbose_name='Hero sectie titel')),
                ('sub_title', wagtail.fields.RichTextField(blank=True, verbose_name='Sub titel')),
                ('hhw_titel', models.CharField(blank=True, max_length=255, verbose_name='HHW Paragraaf titel')),
                ('hhw_paragraaf', wagtail.fields.RichTextField(blank=True, verbose_name='Hoe het werkt')),
            ],
            options={
                'abstract': False,
            },
            bases=('wagtailcore.page',),
        ),
    ]
